name: release
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          # docker run --name fedora -d fedora:39 sleep infinity
          docker run --name fedora -it -d fedora:39 bash
          docker cp . fedora:/busybox-w32
          cat >ci.sh<<EOF
            # rm -rf \`find /etc/yum.repos.d -not -name 'fedora.repo' -not -name 'fedora-updates.repo' -not -name 'yum.repos.d'\`
            podman exec fedora find /etc/yum.repos.d -not -name 'fedora.repo' -not -name 'fedora-updates.repo' -not -name 'yum.repos.d' -print0 | xargs -0 rm -rf
            dnf install mingw64-gcc mingw64-windows-default-manifest diffutils gcc make ncurses-devel perl-Pod-Html bzip2 -y --setopt=install_weak_deps=False --setopt=max_parallel_downloads=8 --setopt=fastestmirror=True
            cd busybox-w32
            make mingw64_defconfig
            make -j`nproc`
          EOF
          docker cp ./ci.sh fedora:/ci.sh
          docker exec fedora sh -c 'chmod +x /ci.sh && /ci.sh'
          docker cp fedora:/busybox-w32/busybox.exe busybox.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: busybox.exe
